// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                   = new(Query)
	User                *user
	UserLog             *userLog
	WorkerWebSearchTask *workerWebSearchTask
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	User = &Q.User
	UserLog = &Q.UserLog
	WorkerWebSearchTask = &Q.WorkerWebSearchTask
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                  db,
		User:                newUser(db, opts...),
		UserLog:             newUserLog(db, opts...),
		WorkerWebSearchTask: newWorkerWebSearchTask(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	User                user
	UserLog             userLog
	WorkerWebSearchTask workerWebSearchTask
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		User:                q.User.clone(db),
		UserLog:             q.UserLog.clone(db),
		WorkerWebSearchTask: q.WorkerWebSearchTask.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		User:                q.User.replaceDB(db),
		UserLog:             q.UserLog.replaceDB(db),
		WorkerWebSearchTask: q.WorkerWebSearchTask.replaceDB(db),
	}
}

type queryCtx struct {
	User                IUserDo
	UserLog             IUserLogDo
	WorkerWebSearchTask IWorkerWebSearchTaskDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		User:                q.User.WithContext(ctx),
		UserLog:             q.UserLog.WithContext(ctx),
		WorkerWebSearchTask: q.WorkerWebSearchTask.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
