// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "goapp/pkg/ids"

const TableNameDevable = "devable"

// Devable mapped from table <devable>
type Devable struct {
	ID   ids.UID `gorm:"column:id;primaryKey" json:"id"`
	Name string  `gorm:"column:name;not null" json:"name"`
}

// TableName Devable's table name
func (*Devable) TableName() string {
	return TableNameDevable
}
