// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "goapp/pkg/ids"

const TableNameUserAccountBinding = "user_account_bindings"

// UserAccountBinding mapped from table <user_account_bindings>
type UserAccountBinding struct {
	ID          ids.UID `gorm:"column:id;primaryKey" json:"id"`
	AccountType int32   `gorm:"column:account_type;not null" json:"accountType"`
	Account     string  `gorm:"column:account;not null" json:"account"`
	Status      int16   `gorm:"column:status" json:"status"`
	StatusText  string  `gorm:"column:status_text;not null" json:"statusText"`
	UserID      ids.UID `gorm:"column:user_id;not null" json:"userId"`
	CreatedAt   int64   `gorm:"column:created_at;not null" json:"createdAt"`
	UpdatedAt   int64   `gorm:"column:updated_at;not null" json:"updatedAt"`
}

// TableName UserAccountBinding's table name
func (*UserAccountBinding) TableName() string {
	return TableNameUserAccountBinding
}
