// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"goapp/pkg/core"
	"goapp/pkg/ids"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        ids.UID     `gorm:"column:id;primaryKey" json:"id"`
	Phone     string      `gorm:"column:phone;not null;comment:如08615900001111" json:"phone"` // 如08615900001111
	Name      string      `gorm:"column:name;not null" json:"name"`
	Password  string      `gorm:"column:password;not null;comment:hash之后的密码" json:"password"` // hash之后的密码
	ThirdAuth core.DBJSON `gorm:"column:third_auth" json:"thirdAuth"`
	Role      int32       `gorm:"column:role;not null" json:"role"`
	Profiles  core.DBJSON `gorm:"column:profiles" json:"profiles"`
	Invite    core.DBJSON `gorm:"column:invite" json:"invite"`
	IP        core.DBJSON `gorm:"column:ip" json:"ip"`
	Status    int32       `gorm:"column:status;not null" json:"status"`
	CreatedAt int64       `gorm:"column:created_at;not null" json:"createdAt"`
	UpdatedAt int64       `gorm:"column:updated_at;not null" json:"updatedAt"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
