// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "goapp/pkg/ids"

const TableNameUserIP = "user_ips"

// UserIP mapped from table <user_ips>
type UserIP struct {
	ID        ids.UID `gorm:"column:id;primaryKey" json:"id"`
	Register  string  `gorm:"column:register;not null" json:"register"`
	Latest    string  `gorm:"column:latest;not null" json:"latest"`
	CreatedAt int64   `gorm:"column:created_at;not null" json:"createdAt"`
	UpdatedAt int64   `gorm:"column:updated_at;not null" json:"updatedAt"`
}

// TableName UserIP's table name
func (*UserIP) TableName() string {
	return TableNameUserIP
}
