// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"goapp/pkg/db"
	"goapp/pkg/ids"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        ids.UID `gorm:"column:id;primaryKey" json:"id"`
	Phone     string  `gorm:"column:phone;not null;comment:如08615900001111" json:"phone"` // 如08615900001111
	Name      string  `gorm:"column:name;not null" json:"name"`
	Password  string  `gorm:"column:password;not null;comment:hash之后的密码" json:"password"` // hash之后的密码
	Role      int32   `gorm:"column:role;not null" json:"role"`
	Profiles  db.JSON `gorm:"column:profiles" json:"profiles"`
	Invite    db.JSON `gorm:"column:invite" json:"invite"`
	Status    int16   `gorm:"column:status;not null" json:"status"`
	CreatedAt int64   `gorm:"column:created_at;not null" json:"createdAt"`
	UpdatedAt int64   `gorm:"column:updated_at;not null" json:"updatedAt"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
