// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "goapp/pkg/core"

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID         core.BigID `gorm:"column:id;primaryKey" json:"id"`
	Phone      string     `gorm:"column:phone;not null;comment:如08615900001111" json:"phone"` // 如08615900001111
	Name       string     `gorm:"column:name;not null" json:"name"`
	Password   string     `gorm:"column:password;not null;comment:hash之后的密码" json:"password"` // hash之后的密码
	AvatarURL  string     `gorm:"column:avatar_url;not null" json:"avatarUrl"`
	Email      string     `gorm:"column:email;not null" json:"email"`
	Role       int32      `gorm:"column:role;not null" json:"role"`
	IPInit     string     `gorm:"column:ip_init;not null" json:"ipInit"`
	IPLatest   string     `gorm:"column:ip_latest;not null" json:"ipLatest"`
	Status     int32      `gorm:"column:status;not null" json:"status"`
	InviteCode string     `gorm:"column:invite_code;not null" json:"inviteCode"`
	InviteBy   int64      `gorm:"column:invite_by;not null" json:"inviteBy"`
	CreatedAt  int64      `gorm:"column:created_at;not null" json:"createdAt"`
	UpdatedAt  int64      `gorm:"column:updated_at;not null" json:"updatedAt"`
	Version    int64      `gorm:"column:version;not null" json:"version"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
