// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserAccountBinding = "user_account_bindings"

// UserAccountBinding 账户绑定，如邮箱，微信等
type UserAccountBinding struct {
	ID          int64  `gorm:"column: id;primaryKey" json:"id"`
	AccountType uint8  `gorm:"column:account_type;not null;comment:账户类型：微信，邮箱等等" json:"accountType"` // 账户类型：微信，邮箱等等
	Account     string `gorm:"column:account;not null;comment:具体账户：邮箱，微信 openid 等" json:"account"`   // 具体账户：邮箱，微信 openid 等
	BoundAt     string `gorm:"column:bound_at;not null;comment:绑定时间" json:"boundAt"`                 // 绑定时间
	Status      uint8  `gorm:"column:status;comment:状态：正常，解绑等等" json:"status"`                       // 状态：正常，解绑等等
}

// TableName UserAccountBinding's table name
func (*UserAccountBinding) TableName() string {
	return TableNameUserAccountBinding
}
