// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWorkerWebSearchTask = "worker_web_search_tasks"

// WorkerWebSearchTask 搜索任务
type WorkerWebSearchTask struct {
	ID       int64  `gorm:"column:id;primaryKey" json:"id"`
	Keywords string `gorm:"column:keywords;not null;comment:搜索词" json:"keywords"` // 搜索词
	CreateAt int64  `gorm:"column:create_at;not null" json:"createAt"`
}

// TableName WorkerWebSearchTask's table name
func (*WorkerWebSearchTask) TableName() string {
	return TableNameWorkerWebSearchTask
}
