name: niu-dev
worker_id: 1

database:
  connect_string: root:abc12345@tcp(127.0.0.1:3306)/niu?charset=utf8mb4&parseTime=True&loc=Local

cache:
  addr: 127.0.0.1:6379
  db: 1

locker:
  addr: 127.0.0.1:6379
  db: 2
  ttl: 15 # 15秒
  retry_strategy: linear # linear or exponential
  backoff: 2 # 2秒
  max_retry: 3

queue:
  addr: 127.0.0.1:6379
  db: 3
  xadd_maxlen: 1024 
  batch_size: 100

hub:
  sub_protocols:
    - niu-v1
  live_check_duration: 120 # 120秒
  conn_max_idle_time: 60   # 60秒
  read_timeout: 30         # 30秒
  write_timeout: 30        # 30秒
  handshake_timeout: 10    # 10秒
  enable_compression: false


authenticator:
  box_key_pair:
    pri: khOEvWcNj0CkvIMGJOaK3FJSp29BWmgJQ15GkK1tXSU
    pub: yAlQ2dupb9qW5HFYCtvoBr6TDlA58UHUGdTTJTWdnAU
  sign_key_pair:
    pri: nS3l3YV9HBJZ3n0fjt_UB5Ek7eqk67Q0yCixs7FnGU4k9NVf7KzEevzc1YW1at22JqEvO1Hne575xy2VaXE_aQ
    pub: JPTVX-ysxHr83NWFtWrdtiahLztR53ue-cctlWlxP2k
  refresh_token_path: /v1/auth/refresh
  paths_need_crypt:
    - "*"
  paths_not_crypt:
    - /v1/auth/login
  paths_need_auth: # 需要验证Token的路径
    - "*"
  paths_not_auth: # 不需要验证Token的路径
    - /v1/auth/login
  jwt:
    issuer: niu
    secret: 1234567890
    access_ttl: 120 # 120分钟
    refresh_ttl: 43200 # 30天
  replay_max_interval: 120 # 120秒
  
cors:
  allow_origins:
    - http://localhost:5173
    - http://127.0.0.1:5173
  allow_methods:
    - GET
    - POST
    - OPTIONS
  allow_headers:
    - Content-Type
    - Authorization
    - Origin
    - Content-Length
    - X-Nonce
    - X-Timestamp
    - X-Signature
    - X-Platform
    - X-Session
  expose_headers: 
    - X-Nonce
    - X-Timestamp
    - X-Signature
  all_credentials: true
  max_age: 120 # 120分钟
  allow_web_sockets: true 
