name: niu-dev
worker_id: 1
db:
  connect_string: root:abc12345@tcp(127.0.0.1:3306)/niu?charset=utf8mb4&parseTime=True&loc=Local

cache:
  addr: 127.0.0.1:6379/0
  slave_addr: 

locker:
  addr: 127.0.0.1:6379/0
  ttl: 15 # 15秒
  retry_strategy: linear # linear or exponential
  backoff: 2 # 2秒
  max_retry: 3

queue:
  addr: 127.0.0.1:6379/0
  xadd_maxlen: 1024 
  batch_size: 100

hub:
  sub_protocols:
    - niu

authenticator:
  redis_addr:
  paths_need_crypt:
    - /api/v1/user/auth 
    - /api/v1/user/refresh
    - /api/v1/user/logout
  paths_not_crypt:
  paths_need_auth: # 需要验证Token的路径
    - "*"
  paths_not_auth: # 不需要验证Token的路径
    - /api/v1/user/auth
  jwt:
    issuer: niu
    secret: 1234567890
    access_ttl: 120 # 120分钟
    refresh_ttl: 720 # 30天
  
cors:
  allow_origins: 
    - https://github.com
  allow_methods:
    - GET
    - POST
    - OPTIONS
  allow_headers:
    - Content-Type
    - Authorization
    - Origin
    - Content-Length
    - X-Nonce
    - X-Timestamp
    - X-Signature
    - X-Platform
  expose_headers: 
    - X-Nonce
    - X-Timestamp
    - X-Signature
  all_credentials: true
  max_age: 120 # 120分钟
  allow_web_sockets: true 
