name: niu-dev
worker_id: 1
addr: 0.0.0.0:8001

database:
  connect_string: root:abc12345@tcp(127.0.0.1:3306)/niu?charset=utf8mb4&parseTime=True&loc=Local

cache:
  addr: 127.0.0.1:6379
  db: 1

locker:
  addr: 127.0.0.1:6379
  db: 2
  ttl: 15 # 15秒
  retry_strategy: linear # linear or exponential
  backoff: 2 # 2秒
  max_retry: 3

queue:
  addr: 127.0.0.1:6379
  db: 3
  xadd_maxlen: 1024 
  batch_size: 100

hub:
  sub_protocols:
    - niu-v1
  live_check_duration: 120 # 120秒
  conn_max_idle_time: 60   # 60秒
  read_timeout: 30         # 30秒
  write_timeout: 30        # 30秒
  handshake_timeout: 10    # 10秒
  enable_compression: false

authenticator:
  box_key_pair:
    pri: WV6RiixviXRntro4x3y3J12ZFgOVw1jfaHBaRvuUD3k
    pub: O6TL8sB1cDQZOEmRYscyPBurNk9Vgw6ezdqOlOTxnSI
  sign_key_pair:
    pri: bkZWXemlxFdUpqrUxYApS2sMbQ1hk1vcfRHMv3AtaJ4
    pub: iO7IS_stxNgDl7m_2vpCY-WrLm-r4VQ7MtopUKNeuMA
  enable_crypto: true
  paths_need_crypt:
    - "*"
  paths_not_crypt:
    - 
  paths_need_auth: # 需要验证Token的路径
    - "*"
  paths_not_auth: # 不需要验证Token的路径
    - /v1/auth/login/prepare
    - /v1/auth/login/do
    - /v1/auth/refresh
  jwt:
    issuer: niu
    secret: 1234567890
    access_ttl: 60 # 120分钟
    refresh_ttl: 43200 # 30天
    cookie_domain: 
    cookie_secure: false
    cookie_httponly: true
    cookie_same_site_mode: 3 # 1: default , 2: lax, 3: strict, 4: none
  replay_max_interval: 120 # 120秒
  
cors:
  allow_origins:
    - http://localhost:3000
    - http://127.0.0.1:3000
  allow_methods:
    - GET
    - POST
    - OPTIONS
  allow_headers:
    - Content-Type
    - Authorization
    - Origin
    - Content-Length
    - Cookie
    - X-Nonce
    - X-Timestamp
    - X-Signature
    - X-Platform
    - X-Session
    - X-Client
  expose_headers: 
    - X-Nonce
    - X-Timestamp
    - X-Signature
    - X-RawType
    - Set-Cookie
  allow_credentials: true
  max_age: 120 # 120分钟
  allow_web_sockets: true 
